### ISSUE TITLE
Create lobby

### ISSUE THREAD

**Issue by Dominionys** [ValvePython/dota2#19]
Hello, 
Can you help with simple example of create lobby?

**Comment by rossengeorgiev** [comment]
Hi, have you looked at the docs? There a bunch of methods for dealing with lobbies

http://dota2.readthedocs.io/en/stable/dota2.features.lobby.html

You can create a lobby easily like this:

```python
dota.create_practice_lobby()
dota.wait_event(dota.EVENT_LOBBY_NEW)

# then you can access the lobby data (read only)
print(dota.lobby)
```

**Comment by Dominionys** [comment]
@rossengeorgiev Yep, thank you :)
