### ISSUE TITLE
Broadcast slot for bot?

### ISSUE THREAD

**Issue by LadaBr** [ValvePython/dota2#26]
Is it possible to launch lobby game with bot in broadcast slot somehow? I always get connection failure because bot couldn't load in.

I would like to get realtime info about match from GC.

**Comment by rossengeorgiev** [comment]
I suspect broadcast slots require the clients to connect to the game server, which is something out of the scope of this project. However, for realtime stats there is a HTTP api that can provide you with ingame stats.

 https://api.steampowered.com/IDOTA2MatchStats_570/GetRealtimeStats/v1?server_steam_id=

The lobby SO should have the `server_steam_id` once the game has started.

**Comment by rossengeorgiev** [comment]
Closing this as it appears resolved
