### ISSUE TITLE
Can't get results from request_matches

### ISSUE THREAD

**Issue by kiddick** [ValvePython/dota2#3]
Here is the code:

``` python
@dota.on('ready')
def fetch_matches():
    jobid = dota.request_matches(account_id=70388657, matches_requested=5)
    resp = dota.wait_event(jobid, timeout=5)
    if resp:
        print resp
```

`resp is None`

I've tried various timeouts..

**Comment by rossengeorgiev** [comment]
That message has been problematic. It might have been disabled completely, as stated in the docs various parameters didn't work before.
