### ISSUE TITLE
get_practice_lobby_list() incomplete results

### ISSUE THREAD

**Issue by ifSomeday** [ValvePython/dota2#32]
Running `dota.get_practice_lobby_list()` returns a list of 5 lobbies. 

There are more than 5 lobbies, and checking the same request using NetHook2 shows that there is indeed more than 5 lobbies returned. The length of the actual result should be ~100 lobbies

**Comment by rossengeorgiev** [comment]
Looks like the method doesn't have kwargs for some of the message fields. It's probably not getting a the full list. Since you've nethooked it already, can provide the contents of `EMsgGCPracticeLobbyList` ?

**Comment by rossengeorgiev** [comment]
The above change adds `get_lobby_list` method, which will get you regular lobbies. Practice lobby list gets you only customs game lobbies.
