### ISSUE TITLE
Recursives calls on chat feature.

### ISSUE THREAD

**Issue by Philaeux** [ValvePython/dota2#34]
Some calls on `self.lobby` and `self.party` create a recursive loop in `dota2.features.chat.ChannelManager`. They must be replaced by `self._dota.party` and `self._dota.lobby`.

Check this function for example: https://github.com/ValvePython/dota2/blob/38682efee6287faadae3b736bbe84a98332d20be/dota2/features/chat.py#L198-L208

**Comment by rossengeorgiev** [comment]
Nice find. Do you want to submit a PR for it?

**Comment by Philaeux** [comment]
I will make one today.
