### ISSUE TITLE
How to get match details after ending

### ISSUE THREAD

**Issue by uturet** [ValvePython/dota2#37]
My bot takes team 4 `DOTA_GC_TEAM_PLAYER_POOL` and haves 
`leaver_status: DOTA_LEAVER_DISCONNECTED`. But during the game events `lobby-removed` and `lobby-changed` contains 
```
...
match_id: 3710000726
game_start_time: 1517418800
...
```
And I can do nothing with it, because properties are missing
```
dota2.util.metadata_url(match_id, cluster, replay_salt, app_id=570)
match_id (int) – match id
cluster (int) – cluster the match is saved on
replay_salt (int) – salt linked to the replay
```
What solutions exists?

**Comment by rossengeorgiev** [comment]
@uturet you need to get the match details. See http://dota2.readthedocs.io/en/latest/dota2.features.match.html#dota2.features.match.Match.request_match_details

**Comment by uturet** [comment]
Thanks for your halp. 
I have this on DEBUG
```
[2018-02-03 17:46:26,979] DEBUG Dota2Client: Emit event: <EDOTAGCMsg.EMsgGCMatchDetailsResponse: 7096>
[2018-02-03 17:46:26,981] DEBUG Dota2Client: Emit event: 'job_4'
[2018-02-03 17:46:26,981] DEBUG Dota2Client: Emit event: 'match_details'
EVENT:  match_details
3715081950
EResult.AccessDenied
None
```
The game are waiting for bot and do not starts when I am trying to play with him in Dire or Radiant team

**Comment by rossengeorgiev** [comment]
The bot can't connect so the game doesn't start. You need to put him as a broadcaster or spectator.
Then after the match has finished you will be able to get match details.

**Comment by liesnikov** [comment]
The problem with this "workaround" is that, due to #26 it isn't possible to launch a match with a bot in broadcaster\spectator slot, and joining it after the match is running doesn't seem to have effect.

(I've tested it quite lightly though)

**Comment by rossengeorgiev** [comment]
I haven't tested that recently, but you could certainly start a match with a bot, and collect the results once the match is finished.

Closing this issue as stale, feel free top reopen if needed.
