### ISSUE TITLE
Start game after coin toss and picked

### ISSUE THREAD

**Issue by thiamhong** [ValvePython/dota2#38]
Does it possible to trigger "Start Game" after coin toss and both team has picked the both team has selected Side/1st pick?

**Comment by rossengeorgiev** [comment]
Hi, itshould be possible to code that. Lobby data, lobby channel and coin toss are function that are available.

**Comment by aut0wash** [comment]
Hi, need some help about this topic.
I would like to use the automatic coin-toss in lobby for pick/side selection.
I thought `self.send(EDOTAGCMsg.EMsgSelectionPriorityChoiceRequest, {})` would work but apparently no.
Any idea on how to do this ?
thx for help
