### ISSUE TITLE
Create many lobbys

### ISSUE THREAD

**Issue by JaroslavL** [ValvePython/dota2#42]
Hello,

Please tell me if I can create a lot of lobbies with different servers? So far I manage to create only one lobby. I would like to be able to create a lot of lobbies. If this is possible with your code, then please tell me.

**Comment by rossengeorgiev** [comment]
It is not possible, and also sounds shady.

**Comment by JaroslavL** [comment]
Thanks for the answer! How does it work on the faceit.com platform? Any bot creates a lobby and invites players. Any idea how to do this?

I assume that they have their own Steam account for each bot. But in this case, there should be a lot of such bot accounts!

**Comment by rossengeorgiev** [comment]
They probably have a lot of accounts.

**Comment by eVen-gits** [comment]
I was looking for just this. Very unfortunate - I would prefer that one account handles multiple lobbies for my inhouse league. Is there no way for this to be done?

Perhaps with a specific dev key or something like that.
