### ISSUE TITLE
Custom game lobby create

### ISSUE THREAD

**Issue by maratkh** [ValvePython/dota2#43]
Hi! Some one can create custom game lobby (for exaple dota 10*10) and start the game eirh real gamer?

Thnx!

**Comment by rossengeorgiev** [comment]
Yes, you can create a custom lobby and start it.

**Comment by maratkh** [comment]
How?

**Comment by rossengeorgiev** [comment]
Use the `create_practice_lobby` method and provide the right settings. The basic functionality is in https://dota2.readthedocs.io/en/stable/dota2.features.lobby.html

You will have to figure out the details.

**Comment by maratkh** [comment]
I can create a custom gsme lobby, but if i stsrt it, bot cant join to game, have any solutions?

**Comment by GTGAMESTUDIO** [comment]
> Use the `create_practice_lobby` method and provide the right settings. The basic functionality is in https://dota2.readthedocs.io/en/stable/dota2.features.lobby.html
> 
> You will need to look at what the dota 2 client does and replicate those details.

Hi, I saw that you were responding to people about the Python Dota2 library (invite to custom lobbies). Could you tell me how this is done?
