### ISSUE TITLE
Move Enum generation code into proto post-processing step

### ISSUE THREAD

**Issue by rossengeorgiev** [ValvePython/dota2#45]
* It won't need to generate enum classes every time at runtime
* Will allows IDEs to autocomplete the enums

**Comment by svenmax** [comment]
Hello, I followed you on Github, I have a request and I hope you can help us.
In our community, we are using a software called Tinserver to play Dota2 on the LAN, but we are missing a GameCoordinator plugin to make it easy for us to build the lobby for the game. I hope you can help us. Thank you very much.

https://cs.rin.ru/forum/viewtopic.php?f=29&t=66246

**Comment by svenmax** [comment]
Hello, I followed you on Github, I have a request and I hope you can help us.
In our community, we are using a software called Tinserver to play Dota2 on the LAN, but we are missing a GameCoordinator plugin to make it easy for us to build the lobby for the game. I hope you can help us. Thank you very much.

https://cs.rin.ru/forum/viewtopic.php?f=29&t=66246
