### ISSUE TITLE
Match details mapping

### ISSUE THREAD

**Issue by OmriGilhar** [ValvePython/dota2#46]
Hi rossengeorgiev,
I recently started to use your wonderful lib, so far all is good, but, when I'm extracting a game detail I get a long and detailed string (dict style) and I'm trying to figure out the meaning of every variable there but I can't find any documentation on this subject, for example:

player_slot: 0
  hero_id: **39**
  item_0: **116**
  item_1: **77**
  item_2: **77**
  item_3: **108**
.
.
.
permanent_buffs {
    permanent_buff: **6**
    stack_count: **1**
  }
  item_6: **0**
  item_7: **0**
  item_8: **0**
  hero_pick_order: 9

Can you please direct me to the mapping documentation?
Thanks!

BTW very nice API and easy to use!

**Comment by rossengeorgiev** [comment]
You can get the from game files:
https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/game/dota/scripts/npc/npc_heroes.txt
Or via the WebAPI:
https://api.steampowered.com/IEconDOTA2_570/GetHeroes/v0001/
https://api.steampowered.com/IEconDOTA2_570/GetGameItems/v0001/
