### ISSUE TITLE
Is it possible to host a match (and download the replay)?

### ISSUE THREAD

**Issue by ipeterov** [ValvePython/dota2#47]
I'm working on a 1v1 practice platform. My bot invites people to lobbies, but the replay is unavailable after the game.

I realized that for the user who hosts a lobby a file like `auto-20191109-0549-start-ipeterov.dem` saved in their replays folder. Is it possible at all with this library to host a game and get this replay? If so, is it implemented?

**Comment by rossengeorgiev** [comment]
Not sure. I don't think replays get recorded for these. If the bot is in the match, he should get access to the match details, you can check there if there is a replay. Then you can pass the match details message to https://dota2.readthedocs.io/en/stable/dota2.util.html#dota2.util.replay_url_from_match to get a url
