### ISSUE TITLE
How can specify protobuf?

### ISSUE THREAD

**Issue by justRoomboy** [ValvePython/dota2#54]
Please show how you can specify protobuf, i can't figure it out. how get proto format and what to write to it?

![image](https://user-images.githubusercontent.com/48877848/91307445-26e95700-e7d8-11ea-82e5-ebd1464ba970.png)

**Comment by rossengeorgiev** [comment]
All protobuf messages are under `dota2.protobufs.xxxxxxxxx`. You need to pass a reference to the message. Together with the EMsg it will build a message for Steam. If it's incorrect or malform, you will either get no response or get kicked off. It rare to need this.

 If the automatic resolution doesn't cover a particular EMsg+message combo, then they should be mapped in code.
