### ISSUE TITLE
KeyError: 'custom_game_auto_created_lobby'

### ISSUE THREAD

**Issue by knkitten** [ValvePython/dota2#71]
File `dota2/protobufs/dota_gcmessages_common_match_management.proto`  has a line 

408	optional bool **custom_game_auto_created_lobby** = 77;

However, when specifying it in the lobby creation options, an error occurs:
`KeyError: 'custom_game_auto_created_lobby'`

**Comment by knkitten** [comment]
Key `all_members` this will throw an identical error too
`KeyError: 'all_members'`

**Comment by FedorAronov** [comment]
@knkitten this message you are talking about is server-to-client.
 [`CMsgPracticeLobbySetDetails`](https://github.com/ValvePython/dota2/blob/6ccebc3689e107746ec32ce07fc2f5cacecc0e18/protobufs/dota_gcmessages_client_match_management.proto#L112) is the correct one.

**Comment by knkitten** [comment]
@Fedya2009 what does the key 'custom_game_penalties' mean?

**Comment by FedorAronov** [comment]
If `custom_game_penalties` is set to `True`, players who leave from game receive 1 hour matchmaking ban (without it, game is safe to leave). 
Also, there is a bug which starts 5 minute leaver countdown for all players when the match begins. Check [Dota 12v12](https://steamcommunity.com/sharedfiles/filedetails/?id=1576297063) for more information.
