### ISSUE TITLE
Can't recieve invite into lobby and GC D2Client doesn't work

### ISSUE THREAD

**Issue by Severes** [ValvePython/dota2#78]
Didn't change code for a year, and it was working
Now i can't do anything with Dota2Client, also i have an error in logs like this:
[2021-11-15 02:11:04,508] ERROR Dota2Client: Failed to parse: -4294967272
Can someone help me, what changed in Game Coordinator? Documentation is the same but it doesnt work...
When i'm trying to get invite into lobby, i can create lobby, but invite is not coming (i have all permissions in steam)

**Comment by k0mar12** [comment]
Yes it is.
I dont remember what exectly, coz half year ago i fixed it too.

**Comment by Severes** [comment]
It looks like Dota2CLient can't get right proto, because it must be a string but incoming as int, That's why in proto() returns None    


```
def _process_gc_message(self, emsg, header, payload):
        emsg = get_emsg_enum(emsg)
        proto = find_proto(emsg)
        message = proto()
        message.ParseFromString(payload) 
```

Maybe u remember anything? Can't find how to fix this

**Comment by Severes** [comment]
Fixed
