### ISSUE TITLE
Implementation of lobby

### ISSUE THREAD

**Issue by DeV1doR** [ValvePython/dota2#8]
Planned:
- [ ] create practice lobby;
- [ ] create tournament lobby;
- [ ] config practice lobby;
- [ ] request practice lobby list;
- [ ] request friend practice lobby list;
- [ ] balanced shuffle lobby;
- [ ] flip lobby teams;
- [ ] invite to lobby;
- [ ] practice lobby kick;
- [ ] practice lobby kick from team;
- [ ] join practice lobby;
- [ ] leave practice lobby;
- [ ] abandon current game;
- [ ] launch practice lobby;
- [ ] join practice lobby team;
- [ ] join practice lobby broadcast channel;
- [ ] add bot to practice lobby;
- [ ] respond party invite;

TODO:
- check another handlers on events and implement here;
- update docs;

**Comment by rossengeorgiev** [comment]
Resolved in #10
