### ISSUE TITLE
Lobby Options Keys/Values

### ISSUE THREAD

**Issue by maxcwbender** [ValvePython/dota2#83]
Hello!

I'm a little confused on the creation of lobbies. I see that there is an optional dictionary input that could specify the lobby settings, but it isn't immediately obvious to me what the keys/values ought to be. Is there any resource I could track down that would specify this?

**Comment by maxcwbender** [comment]
It seems like some of the options might be detailed here, but the interpretation of some of the values seems to be left to imagination: https://github.com/ValvePython/dota2/blob/ca75440adca20d852b9aec3917e4387466848d5b/protobufs/dota_gcmessages_common_match_management.proto#L193

**Comment by rossengeorgiev** [comment]
Yes, options would be a `dict` to fill in the options in this message https://github.com/ValvePython/dota2/blob/ca75440adca20d852b9aec3917e4387466848d5b/protobufs/dota_gcmessages_client_match_management.proto#L88-L132

These may be out of date since I haven't touched this package in a long time.

What should be the options to set? I don't know, you will have to use NetHook to see what the Dota 2 game.

**Comment by maxcwbender** [comment]
Thank you!

**Comment by vilad86** [comment]
> Yes, options would be a `dict` to fill in the options in this message
> 
> https://github.com/ValvePython/dota2/blob/ca75440adca20d852b9aec3917e4387466848d5b/protobufs/dota_gcmessages_client_match_management.proto#L88-L132
> 
> These may be out of date since I haven't touched this package in a long time.
> 
> What should be the options to set? I don't know, you will have to use NetHook to see what the Dota 2 game.

Hello, I have a number of questions. Please be understanding with me, I am new to programming. And I’ll probably say a lot of stupid things.

1) What is NetHook?
2) How to update Protobuffs?
3) How to get what can be specified in the message parameters in a get request?
3.1) In other words, how to find out what’s new, what new lines have appeared, how to find out?
