### ISSUE TITLE
dota.launch() always results in Dota2Client: Failed to parse -4294963292

### ISSUE THREAD

**Issue by rpatel1023** [ValvePython/dota2#92]
I'm attempting to use the Dota2Client with SteamClient in my environment and consistently fail to create a session with the D2Client.
It appears the same issue occured at #78 but there isn't much explanation as to how it was resolved, but the issue is likely described correctly, where the proto is being received as an integer instead of it's intended type. Any help would be appreciated

**Comment by k0mar12** [comment]
Do you have a fresh protos ?

**Comment by rpatel1023** [comment]
i have a new environment and just installed the library, so i'm assuming yes? but I may be misinterpreting what that means

**Comment by rpatel1023** [comment]
I was able to resolve the problem, it seems that I was running a 32-bit version of Python, reinstalled with 64-bit and it fixed.
